# Generated by Django 3.1.7 on 2021-03-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=255)),
                ('year', models.DateTimeField()),
                ('poster', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('casts', models.ManyToManyField(to='movie.Cast')),
                ('countries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.country')),
                ('tags', models.ManyToManyField(to='movie.Category')),
            ],
        ),
    ]
